name: CI

name: CI
on:
  pull_request:
    branches:
    - master
  push:
    branches:
      - master

jobs:
  concurrency:
    group: ${{ main }}
    cancel-in-progress: true

# Canceling since a higher priority waiting request for 'pages build and deployment @ main' exists
